name: main
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron:  '0 7 * * *'

jobs:
  linux:
    runs-on: ubuntu-latest

    env:
      ZKG_LIB: ./zig-cache/lib/zig/zkg

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1.2.5
      with:
        version: master

    - name: Install libgit2
      run: sudo apt install libgit2-dev

    - name: Compile
      run: zig build

    - name: Init
      run: ./zig-cache/bin/zkg init

    - name: Search
      run: ./zig-cache/bin/zkg search

    - name: Add
      run: ./zig-cache/bin/zkg add clap

    - name: Fetch
      run: ./zig-cache/bin/zkg fetch

  macos:
    runs-on: macos-latest
    env:
      ZKG_LIB: ./zig-cache/lib/zig/zkg

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1.2.5
      with:
        version: master

    - name: Install libgit2
      run: brew install libgit2

    - name: Compile
      run: zig build

    - name: Init
      run: ./zig-cache/bin/zkg init

    - name: Search
      run: ./zig-cache/bin/zkg search

    - name: Add
      run: ./zig-cache/bin/zkg add clap

    - name: Fetch
      run: ./zig-cache/bin/zkg fetch
