name: main

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ZKG_LIB: $GITHUB_WORKSPACE/zkg/zig-cache/lib/zig/zkg

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive 

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1.2.5
      with:
        version: master

    - name: Install libgit2
      run: sudo apt install libgit2-dev

    - name: Compile
      run: zig build
    
    - name: Init
      run: ./zig-cache/bin/zkg init

    - name: Search
      run: ./zig-cache/bin/zkg search

    - name: Add
      run: ./zig-cache/bin/zkg add clap
    
    - name: Fetch
      run: ./zig-cache/bin/zkg fetch
