name: main

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive 

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1.2.5
      with:
        version: master

    - name: Compile
      run: zig build
    
    - run: export PATH=$PATH:$(pwd)/zig-cache/bin
    - run: cd ~ && mkdir test-project && cd test-project
    
    - name: Zkg init
      run: zkg init

    - name: Zkg search
      run: zkg search

    - name: Zkg add
      run: zkg add clap
    
    - name: Zkg fetch
      run: zkg fetch
