name: main

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive 

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1.2.5
      with:
        version: master

    - name: Install libgit2
      run: sudo apt install libgit2-dev

    - name: Compile
      run: zig build
    
    - name: Zkg init
      run: ./zig-cache/bin/zkg init

    - name: Zkg search
      run: ./zig-cache/bin/zkg search

    - name: Zkg add
      run: ./zig-cache/bin/zkg add clap
    
    - name: Zkg fetch
      run: ./zig-cache/bin/zkg fetch
